[package]
name = "SshAnalyser"
version = "0.1.0"
authors = ["0xd34db33f <0xd34db33f@noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2="0.6.0"
clap="2.33.0"
evmap = "7.1.3"